<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82033" started-at="2018-11-22T16:22:48Z" finished-at="2018-11-22T16:24:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82033" started-at="2018-11-22T16:22:48Z" finished-at="2018-11-22T16:24:10Z">
      <class name="Railway.LoginTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="4620" started-at="2018-11-22T16:22:48Z" finished-at="2018-11-22T16:22:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC01()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC01" duration-ms="9251" started-at="2018-11-22T16:22:53Z" description="User can log into Railway with valid username and password" finished-at="2018-11-22T16:23:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="1031" started-at="2018-11-22T16:23:02Z" finished-at="2018-11-22T16:23:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="3659" started-at="2018-11-22T16:23:03Z" finished-at="2018-11-22T16:23:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC02" duration-ms="8201" started-at="2018-11-22T16:23:07Z" description="User can&#039;t login with blank &quot;Username&quot; textbox" finished-at="2018-11-22T16:23:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="597" started-at="2018-11-22T16:23:15Z" finished-at="2018-11-22T16:23:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="3666" started-at="2018-11-22T16:23:16Z" finished-at="2018-11-22T16:23:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC03()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC03" duration-ms="8523" started-at="2018-11-22T16:23:19Z" description="User cannot log into Railway with invalid password " finished-at="2018-11-22T16:23:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The text should be: There was a problem with your login and/or errors exist in your form. expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The text should be: There was a problem with your login and/or errors exist in your form. expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Common.Utilities.checkTextDisplays(Utilities.java:24)
at Railway.LoginTest.TC03(LoginTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="579" started-at="2018-11-22T16:23:28Z" finished-at="2018-11-22T16:23:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="3677" started-at="2018-11-22T16:23:28Z" finished-at="2018-11-22T16:23:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC04()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC04" duration-ms="7006" started-at="2018-11-22T16:23:32Z" description="Login page displays when un-logged User clicks on &quot;Book ticket&quot; tab" finished-at="2018-11-22T16:23:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="987" started-at="2018-11-22T16:23:39Z" finished-at="2018-11-22T16:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="3663" started-at="2018-11-22T16:23:40Z" finished-at="2018-11-22T16:23:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC05" duration-ms="10983" started-at="2018-11-22T16:23:44Z" description="System shows message when user enters wrong password several times" finished-at="2018-11-22T16:23:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The text should be: You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes. expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The text should be: You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes. expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Common.Utilities.checkTextDisplays(Utilities.java:24)
at Railway.LoginTest.TC05(LoginTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="591" started-at="2018-11-22T16:23:55Z" finished-at="2018-11-22T16:23:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="beforeMethod" is-config="true" duration-ms="3616" started-at="2018-11-22T16:23:55Z" finished-at="2018-11-22T16:23:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC06()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="TC06" duration-ms="10747" started-at="2018-11-22T16:23:59Z" description="Additional pages display once user logged in" finished-at="2018-11-22T16:24:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Railway.LoginTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="584" started-at="2018-11-22T16:24:10Z" finished-at="2018-11-22T16:24:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Railway.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
